const mongoose = require('mongoose');

// Room
// id - autogenerated
// name - Room name

const RoomSchema = mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      unique: true,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Room', RoomSchema);
